version: '3.8'

services:
  golang-app:
    build: .
    container_name: basic-golang-api
    ports:
      - "8082:8080"  # Expose port 8080 to the host machine
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
